import {
  TIME_SELECTION_WHENEVER,
  TIME_SELECTION_WHENEVER_PARAM,
  TIME_SELECTION_TODAY,
  TIME_SELECTION_TODAY_PARAM,
  TIME_SELECTION_TOMORROW,
  TIME_SELECTION_TOMORROW_PARAM,
  TIME_SELECTION_THISWEEK,
  TIME_SELECTION_THISWEEK_PARAM
} from './Constants'

export const TIME_SELECTION_VALUES = [
  {text: TIME_SELECTION_WHENEVER, param: TIME_SELECTION_WHENEVER_PARAM},
  {text: TIME_SELECTION_TODAY, param: TIME_SELECTION_TODAY_PARAM},
  {text: TIME_SELECTION_TOMORROW, param: TIME_SELECTION_TOMORROW_PARAM},
  {text: TIME_SELECTION_THISWEEK, param: TIME_SELECTION_THISWEEK_PARAM}
]
